### ISSUE TITLE
what name for the .env file?

### ISSUE THREAD

**Issue by federicobetta** [mrtolkien/kindle_to_notion#2]
Dear,
Sorry, I'm a newbie.

This is the terminal output. What did I accomplish wrong?

Thank you

Last login: Tue Jun 11 15:16:58 on ttys001
/Volumes/Kindle/kindle_to_notion_mac_arm ; exit;                                
macbook@MacBookPro-di-K ~ % /Volumes/Kindle/kindle_to_notion_mac_arm ; exit;
thread 'main' panicked at '.env file not found: Io(Custom { kind: NotFound, error: "path not found" })', src/main.rs:10:23
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by mrtolkien** [comment]
Just `.env`
